
///////////////////////////////////////////////////////////////////////////////
//
// THIS FILE IS AUTOGENERATED BY GYP_TO_ANDROID.PY. DO NOT EDIT.
//
// This file contains Skia's upstream include/config/SkUserConfig.h as a
// reference, followed by the actual defines set for Android.
//
///////////////////////////////////////////////////////////////////////////////


// Android defines:
#ifndef SkUserConfig_Android_DEFINED
#define SkUserConfig_Android_DEFINED
#ifdef ANDROID
    #include <utils/misc.h>
#endif

#if __BYTE_ORDER == __BIG_ENDIAN
    #define SK_CPU_BENDIAN
    #undef  SK_CPU_LENDIAN
#else
    #define SK_CPU_LENDIAN
    #undef  SK_CPU_BENDIAN
#endif

#define SK_INTERNAL
#define SK_GAMMA_APPLY_TO_A8
#define SK_SCALAR_TO_FLOAT_EXCLUDED
#define SK_ALLOW_STATIC_GLOBAL_INITIALIZERS 0
#define SK_SUPPORT_GPU 1
#define SK_SUPPORT_OPENCL 0
#define SK_FORCE_DISTANCEFIELD_FONTS 0
#define SK_SCALAR_IS_FLOAT
#define SK_CAN_USE_FLOAT
#define DCT_IFAST_SUPPORTED
#define SK_USE_FREETYPE_EMBOLDEN
#define SK_SFNTLY_SUBSETTER "sample/chromium/font_subsetter.h"
#define SK_BUILD_FOR_ANDROID_FRAMEWORK
#define GR_GL_CUSTOM_SETUP_HEADER "gl/GrGLConfig_chrome.h"
#define IGNORE_ROT_AA_RECT_OPT
#define SK_DISABLE_PIXELREF_LOCKCOUNT_BALANCE_CHECK
#define SkLONGLONG int64_t
#define SK_DEFAULT_FONT_CACHE_LIMIT   (768 * 1024)
#define SK_ATOMICS_PLATFORM_H "../../src/ports/SkAtomics_sync.h"
#define SK_MUTEX_PLATFORM_H "../../src/ports/SkMutex_pthread.h"
#define kNative_8888_SkColorType kN32_SkColorType
#define SK_SUPPORT_LEGACY_CLIPTOLAYERFLAG
#define SK_ATTR_DEPRECATED SK_NOTHING_ARG1
#define SK_SUPPORT_LEGACY_SHADER_LOCALMATRIX
#define SK_DEFAULT_GLOBAL_DISCARDABLE_MEMORY_POOL_SIZE (512 * 1024)
#define SK_IGNORE_ETC1_SUPPORT
#define SK_SUPPORT_LEGACY_SETCONFIG_INFO
#define SK_SUPPORT_LEGACY_SETCONFIG
#define SK_SUPPORT_LEGACY_IMAGEDECODER_CONFIG
#define SK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE
#define SK_SUPPORT_LEGACY_BITMAP_CONFIG
#define SK_SUPPORT_LEGACY_COMPUTE_CONFIG_SIZE
#define SK_BUILD_FOR_ANDROID
#define SK_FONTHOST_DOES_NOT_USE_FONTMGR
#define SK_GAMMA_EXPONENT 1.4
#define SK_GAMMA_CONTRAST 0.0
#define SK_USE_POSIX_THREADS
#define SK_FONTHOST_FREETYPE_RUNTIME_VERSION 0x020400
#define SK_CAN_USE_DLOPEN 0
#define GR_COMPRESS_ALPHA_MASK 0
#define SK_SUPPORT_PDF

#endif // SkUserConfig_Android_DEFINED
